### PR TITLE
ci: test Python 3.6 on AppVeyor

### PR DESCRIPTION
**Pull request by schlamar**

### CODE REVIEW

**Comment by saghul** [comment]
Hey there! The failure on Travis seems like a Travis issue, but the AppVeyor one could somehow be legit.

**Comment by schlamar** [comment]
Oh yes, there is really a regression in 3.6+ (see Travis). Any idea?

**Comment by schlamar** [comment]
Please see: https://bugs.python.org/issue26685

I guess we should just remove the `sock.close` call?!

**Comment by schlamar** [comment]
Not sure about the UDP test case though. There is a different behavior on Linux and Windows. Is pyuv or libuv closing the underlying socket on bind error on Linux?

**Comment by schlamar** [comment]
Oh yes. libuv closes the underlying socket on bind error on Linux (https://github.com/libuv/libuv/blob/d898a1f6f87ba30e7803fe402121464553b2ffaf/src/unix/udp.c#L343) but not on Windows (https://github.com/libuv/libuv/blob/87df1448a48fb64c2b9ebe37e3344f7e5b81dd88/src/win/udp.c#L261).

**Comment by schlamar** [comment]
Reported upstream: https://github.com/libuv/libuv/issues/1336

**Comment by saghul** [comment]
Thanks for digging though it! I think the current workaround looks ok!

**Comment by schlamar** [comment]
Are you planning a new release any time soon? If not we could create a temporary branch based on the pyuv-1.3.0 tag with these changes so AppVeyor is building the Python 3.6 wheels for 1.3.0. :)

**Comment by schlamar** [comment]
@saghul Ping :)

**Comment by schlamar** [comment]
@saghul Should I squash this in one commit? `ci,test: add proper support for Python 3.6`?

**Comment by schlamar** [comment]
New proposal (see commits)

**Comment by schlamar** [comment]
BTW, setuptools has broken the Travis builds :/

https://github.com/pypa/setuptools/issues/1042

**Pull request merged**
